// <auto-generated />
using System;
using BloodDonationSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonationSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212061937_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodDonationSystem.Models.BloodBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.ToTable("BloodBanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodTypeId = 1,
                            quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            BloodTypeId = 2,
                            quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            BloodTypeId = 3,
                            quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            BloodTypeId = 4,
                            quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            BloodTypeId = 5,
                            quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            BloodTypeId = 6,
                            quantity = 5
                        },
                        new
                        {
                            Id = 7,
                            BloodTypeId = 7,
                            quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            BloodTypeId = 8,
                            quantity = 5
                        });
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodBankHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodBankId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBloodAdded")
                        .HasColumnType("bit");

                    b.Property<int>("QuantityTransaction")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.ToTable("BloodBankHistory");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BloodRequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.ToTable("BloodRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodRequestDate = new DateTime(2026, 2, 11, 22, 19, 36, 396, DateTimeKind.Local).AddTicks(5355),
                            BloodTypeId = 1,
                            IsActive = false,
                            Quantity = 5,
                            isApproved = false
                        });
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodTypeName = "A+"
                        },
                        new
                        {
                            Id = 2,
                            BloodTypeName = "A-"
                        },
                        new
                        {
                            Id = 3,
                            BloodTypeName = "B+"
                        },
                        new
                        {
                            Id = 4,
                            BloodTypeName = "B-"
                        },
                        new
                        {
                            Id = 5,
                            BloodTypeName = "AB+"
                        },
                        new
                        {
                            Id = 6,
                            BloodTypeName = "AB-"
                        },
                        new
                        {
                            Id = 7,
                            BloodTypeName = "O+"
                        },
                        new
                        {
                            Id = 8,
                            BloodTypeName = "O-"
                        });
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DonationSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("WhenUserWantToDonate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BloodRequestId");

                    b.HasIndex("DonorId");

                    b.HasIndex("StatusId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Donor"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Hospital"
                        });
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            StatusName = "Rejected"
                        },
                        new
                        {
                            Id = 5,
                            StatusName = "Approved"
                        });
                });

            modelBuilder.Entity("BloodDonationSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UserCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hospital.com",
                            Name = "admin",
                            PhoneNumber = "1234567890",
                            UserCreationDate = new DateTime(2026, 2, 11, 22, 19, 36, 396, DateTimeKind.Local).AddTicks(5138),
                            password = "$2a$11$kYhEbUzfsy.wDPKHTNPJjOxvydA3Rxc90hnSvSqprtsggk/Is3I5q"
                        });
                });

            modelBuilder.Entity("BloodDonationSystem.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("RoleAssignDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodBank", b =>
                {
                    b.HasOne("BloodDonationSystem.Models.BloodType", "BloodType")
                        .WithMany("BloodBanks")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodBankHistory", b =>
                {
                    b.HasOne("BloodDonationSystem.Models.BloodBank", "BloodBank")
                        .WithMany("BloodTakenFromBloodBanks")
                        .HasForeignKey("BloodBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodBank");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodRequest", b =>
                {
                    b.HasOne("BloodDonationSystem.Models.BloodType", "BloodType")
                        .WithMany("BloodRequests")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Donation", b =>
                {
                    b.HasOne("BloodDonationSystem.Models.BloodRequest", "BloodRequest")
                        .WithMany("Donations")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationSystem.Models.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationSystem.Models.Status", "Status")
                        .WithMany("Donations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Donor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Donor", b =>
                {
                    b.HasOne("BloodDonationSystem.Models.BloodType", "BloodType")
                        .WithMany("Donors")
                        .HasForeignKey("BloodTypeId");

                    b.HasOne("BloodDonationSystem.Models.User", "User")
                        .WithOne("Donors")
                        .HasForeignKey("BloodDonationSystem.Models.Donor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.UserRole", b =>
                {
                    b.HasOne("BloodDonationSystem.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationSystem.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodBank", b =>
                {
                    b.Navigation("BloodTakenFromBloodBanks");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodRequest", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.BloodType", b =>
                {
                    b.Navigation("BloodBanks");

                    b.Navigation("BloodRequests");

                    b.Navigation("Donors");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.Status", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("BloodDonationSystem.Models.User", b =>
                {
                    b.Navigation("Donors")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
